/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Houses_FirstAge_1_Level1.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube030.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Cube030_1.geometry} material={materials.Stone} />
    </group>
  )
}

useGLTF.preload('/Houses_FirstAge_1_Level1.gltf')
