/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PostsIndexImport } from './routes/posts_/index'
import { Route as HelloIndexImport } from './routes/hello/index'
import { Route as PostslayoutImport } from './routes/posts_/_layout'
import { Route as PostsPostIdImport } from './routes/posts_/$postId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIndexRoute = PostsIndexImport.update({
  path: '/posts/',
  getParentRoute: () => rootRoute,
} as any)

const HelloIndexRoute = HelloIndexImport.update({
  path: '/hello/',
  getParentRoute: () => rootRoute,
} as any)

const PostslayoutRoute = PostslayoutImport.update({
  path: '/posts/_layout',
  getParentRoute: () => rootRoute,
} as any)

const PostsPostIdRoute = PostsPostIdImport.update({
  path: '/posts/$postId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/$postId': {
      preLoaderRoute: typeof PostsPostIdImport
      parentRoute: typeof rootRoute
    }
    '/posts/_layout': {
      preLoaderRoute: typeof PostslayoutImport
      parentRoute: typeof rootRoute
    }
    '/hello/': {
      preLoaderRoute: typeof HelloIndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/': {
      preLoaderRoute: typeof PostsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  PostsPostIdRoute,
  PostslayoutRoute,
  HelloIndexRoute,
  PostsIndexRoute,
])

/* prettier-ignore-end */
