/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useRef } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"
import { GLTF } from "three-stdlib"
import { createModel } from "../lib/createModel"
import mergeRefs from "react-merge-refs"

type GLTFResult = GLTF & {
  nodes: {
    Cube063: THREE.SkinnedMesh
    Cube063_1: THREE.SkinnedMesh
    Cube063_2: THREE.SkinnedMesh
    Cube052: THREE.SkinnedMesh
    Cube052_1: THREE.SkinnedMesh
    Cube039: THREE.SkinnedMesh
    Cube039_1: THREE.SkinnedMesh
    Cube039_2: THREE.SkinnedMesh
    Cube039_3: THREE.SkinnedMesh
    Cube020: THREE.SkinnedMesh
    Cube020_1: THREE.SkinnedMesh
    Plane: THREE.SkinnedMesh
    Plane_1: THREE.SkinnedMesh
    Plane_2: THREE.SkinnedMesh
    Plane_3: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: {
    Skin: THREE.MeshStandardMaterial
    Green: THREE.MeshStandardMaterial
    LightGreen: THREE.MeshStandardMaterial
    Grey: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Eyebrows: THREE.MeshStandardMaterial
    Hair: THREE.MeshStandardMaterial
    Eye: THREE.MeshStandardMaterial
    Brown: THREE.MeshStandardMaterial
    Brown2: THREE.MeshStandardMaterial
    Gold: THREE.MeshStandardMaterial
  }
  animations: { name: ActionName }
}

type ActionName =
  | "Death"
  | "Gun_Shoot"
  | "HitRecieve"
  | "HitRecieve_2"
  | "Idle"
  | "Idle_Gun"
  | "Idle_Gun_Pointing"
  | "Idle_Gun_Shoot"
  | "Idle_Neutral"
  | "Idle_Sword"
  | "Interact"
  | "Kick_Left"
  | "Kick_Right"
  | "Punch_Left"
  | "Punch_Right"
  | "Roll"
  | "Run"
  | "Run_Back"
  | "Run_Left"
  | "Run_Right"
  | "Run_Shoot"
  | "Sword_Slash"
  | "Walk"
  | "Wave"
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export const Adventurer = createModel<GLTFResult>(
  "/animals/Adventurer.gltf",
  ({ group, nodes, materials, ref, ...props }) => {
    return (
      <group ref={group} {...props} dispose={null}>
        <group name="Scene">
          <group name="CharacterArmature">
            <primitive object={nodes.Root} />
            <group name="Adventurer_Body">
              <skinnedMesh
                name="Cube063"
                geometry={nodes.Cube063.geometry}
                material={materials.Skin}
                skeleton={nodes.Cube063.skeleton}
              />
              <skinnedMesh
                name="Cube063_1"
                geometry={nodes.Cube063_1.geometry}
                material={materials.Green}
                skeleton={nodes.Cube063_1.skeleton}
              />
              <skinnedMesh
                name="Cube063_2"
                geometry={nodes.Cube063_2.geometry}
                material={materials.LightGreen}
                skeleton={nodes.Cube063_2.skeleton}
              />
            </group>
            <group name="Adventurer_Feet">
              <skinnedMesh
                name="Cube052"
                geometry={nodes.Cube052.geometry}
                material={materials.Grey}
                skeleton={nodes.Cube052.skeleton}
              />
              <skinnedMesh
                name="Cube052_1"
                geometry={nodes.Cube052_1.geometry}
                material={materials.Black}
                skeleton={nodes.Cube052_1.skeleton}
              />
            </group>
            <group name="Adventurer_Head">
              <skinnedMesh
                name="Cube039"
                geometry={nodes.Cube039.geometry}
                material={materials.Skin}
                skeleton={nodes.Cube039.skeleton}
              />
              <skinnedMesh
                name="Cube039_1"
                geometry={nodes.Cube039_1.geometry}
                material={materials.Eyebrows}
                skeleton={nodes.Cube039_1.skeleton}
              />
              <skinnedMesh
                name="Cube039_2"
                geometry={nodes.Cube039_2.geometry}
                material={materials.Hair}
                skeleton={nodes.Cube039_2.skeleton}
              />
              <skinnedMesh
                name="Cube039_3"
                geometry={nodes.Cube039_3.geometry}
                material={materials.Eye}
                skeleton={nodes.Cube039_3.skeleton}
              />
            </group>
            <group name="Adventurer_Legs">
              <skinnedMesh
                name="Cube020"
                geometry={nodes.Cube020.geometry}
                material={materials.Brown}
                skeleton={nodes.Cube020.skeleton}
              />
              <skinnedMesh
                name="Cube020_1"
                geometry={nodes.Cube020_1.geometry}
                material={materials.Brown2}
                skeleton={nodes.Cube020_1.skeleton}
              />
            </group>
            <group name="Backpack">
              <skinnedMesh
                name="Plane"
                geometry={nodes.Plane.geometry}
                material={materials.Brown}
                skeleton={nodes.Plane.skeleton}
              />
              <skinnedMesh
                name="Plane_1"
                geometry={nodes.Plane_1.geometry}
                material={materials.LightGreen}
                skeleton={nodes.Plane_1.skeleton}
              />
              <skinnedMesh
                name="Plane_2"
                geometry={nodes.Plane_2.geometry}
                material={materials.Gold}
                skeleton={nodes.Plane_2.skeleton}
              />
              <skinnedMesh
                name="Plane_3"
                geometry={nodes.Plane_3.geometry}
                material={materials.Green}
                skeleton={nodes.Plane_3.skeleton}
              />
            </group>
          </group>
        </group>
      </group>
    )
  }
)

useGLTF.preload("/animals/Adventurer.gltf")
