/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ArtaSculpts (https://sketchfab.com/Artahir)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-sekiro-f9d7ca6a005c47798f6fbb92ca9887d0
title: Low-Poly Sekiro
*/

import * as THREE from "three"
import React, { forwardRef, useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    Cylinder_Hair_0: THREE.Mesh
    Cube004_Face_0: THREE.Mesh
    Cube004_Hair_0: THREE.Mesh
    Cube004_Scarf_0: THREE.Mesh
    Cylinder001_Bandages_0: THREE.Mesh
    Hand_Grey_0: THREE.Mesh
    Hand_Face_0: THREE.Mesh
    Prosthetic_Metal_0: THREE.Mesh
    Prosthetic_light_grey_0: THREE.Mesh
    Prosthetic_Bone_0: THREE.Mesh
    Prosthetic_Scarf_0: THREE.Mesh
    Prosthetic_Bone_light_0: THREE.Mesh
    Cylinder004_Bandages_0: THREE.Mesh
    Arm_Grey_0: THREE.Mesh
    Arm_Bandages_0: THREE.Mesh
    Scarf_Scarf_0: THREE.Mesh
    Cube000_Grey_0: THREE.Mesh
    Plane_New_Coat_0: THREE.Mesh
    Cube003_Material003_0: THREE.Mesh
    Cylinder002_Bandages_0: THREE.Mesh
    Legs_Grey_0: THREE.Mesh
    Legs_Pants_0: THREE.Mesh
    Legs_Dark_red_0: THREE.Mesh
    Legs_Scarf_0: THREE.Mesh
    Legs_Red_0: THREE.Mesh
    _Sword000_Black_0: THREE.Mesh
    _Sword000_Metal_0: THREE.Mesh
    _Sword000_Bronze_0: THREE.Mesh
    Cube002_Bandages_0: THREE.Mesh
    _Sword002_Sword_red_0: THREE.Mesh
    _Sword002_Red_Metal_0: THREE.Mesh
    _Sword002_Black_0: THREE.Mesh
    Cube006_Red_0: THREE.Mesh
    Jacket_Dark_red_0: THREE.Mesh
    Jacket_Grey_0: THREE.Mesh
    Jacket_light_grey_0: THREE.Mesh
    Jacket_Scarf_0: THREE.Mesh
  }
  materials: {
    Hair: THREE.MeshStandardMaterial
    Face: THREE.MeshStandardMaterial
    Scarf: THREE.MeshStandardMaterial
    Bandages: THREE.MeshStandardMaterial
    Grey: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    light_grey: THREE.MeshStandardMaterial
    Bone: THREE.MeshStandardMaterial
    Bone_light: THREE.MeshStandardMaterial
    New_Coat: THREE.MeshStandardMaterial
    ["Material.003"]: THREE.MeshStandardMaterial
    Pants: THREE.MeshStandardMaterial
    Dark_red: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Bronze: THREE.MeshStandardMaterial
    Sword_red: THREE.MeshStandardMaterial
    Red_Metal: THREE.MeshStandardMaterial
  }
}

export const CharacterModel = forwardRef(
  (props: JSX.IntrinsicElements["group"], ref) => {
    const { nodes, materials } = useGLTF(
      "/models/low-poly_sekiro.glb"
    ) as GLTFResult
    return (
      <group
        {...props}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2}
        position={[0, -2, 0]}
        dispose={null}
        ref={ref}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_Hair_0.geometry}
          material={materials.Hair}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_Face_0.geometry}
          material={materials.Face}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_Hair_0.geometry}
          material={materials.Hair}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_Scarf_0.geometry}
          material={materials.Scarf}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_Bandages_0.geometry}
          material={materials.Bandages}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hand_Grey_0.geometry}
          material={materials.Grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hand_Face_0.geometry}
          material={materials.Face}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Prosthetic_Metal_0.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Prosthetic_light_grey_0.geometry}
          material={materials.light_grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Prosthetic_Bone_0.geometry}
          material={materials.Bone}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Prosthetic_Scarf_0.geometry}
          material={materials.Scarf}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Prosthetic_Bone_light_0.geometry}
          material={materials.Bone_light}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_Bandages_0.geometry}
          material={materials.Bandages}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arm_Grey_0.geometry}
          material={materials.Grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arm_Bandages_0.geometry}
          material={materials.Bandages}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Scarf_Scarf_0.geometry}
          material={materials.Scarf}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube000_Grey_0.geometry}
          material={materials.Grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_New_Coat_0.geometry}
          material={materials.New_Coat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_Material003_0.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_Bandages_0.geometry}
          material={materials.Bandages}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Legs_Grey_0.geometry}
          material={materials.Grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Legs_Pants_0.geometry}
          material={materials.Pants}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Legs_Dark_red_0.geometry}
          material={materials.Dark_red}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Legs_Scarf_0.geometry}
          material={materials.Scarf}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Legs_Red_0.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._Sword000_Black_0.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._Sword000_Metal_0.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._Sword000_Bronze_0.geometry}
          material={materials.Bronze}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_Bandages_0.geometry}
          material={materials.Bandages}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._Sword002_Sword_red_0.geometry}
          material={materials.Sword_red}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._Sword002_Red_Metal_0.geometry}
          material={materials.Red_Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes._Sword002_Black_0.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_Red_0.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Jacket_Dark_red_0.geometry}
          material={materials.Dark_red}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Jacket_Grey_0.geometry}
          material={materials.Grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Jacket_light_grey_0.geometry}
          material={materials.light_grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Jacket_Scarf_0.geometry}
          material={materials.Scarf}
        />
      </group>
    )
  }
)

useGLTF.preload("/models/low-poly_sekiro.glb")
